version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://127.0.0.1:27017/e-commerce
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
