version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BACKEND=192.168.0.11
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://database:27017/e-commerce
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
