version: "3.8"

services:
  database:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://database:27017/e-commerce
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - database
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
