apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: e-com
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
