apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: e-com
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/db
  claimRef:
    namespace: e-com
    name: mongo-pvc
