apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: e-com
spec:
  selector:
    role: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
