apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: e-com
  labels:
    role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
        - name: backend-e-com
          image: faizan44/e-com_micro_backend
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGODB_URI
              value: "mongodb://db-svc:27017/e-commerce"
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
