apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: e-com
spec:
  selector:
    app: mongo
  ports:
    - name: mongodb-service
      protocol: TCP
      port: 27017
      targetPort: 27017
